#!/bin/bash

## Generate the sequence of JPEG images.
TMPDIR=$(mktemp -d)
convert -quality 85 $1 ${TMPDIR}/mock-frame-%02d.jpg

## Pack the frames into a single source file.
cat << EOF
/* Automatically generated by "$0" -- Do Not Edit */
#include <stdint.h>
#include "mock.h"
EOF

NUM=0
for NAME in ${TMPDIR}/*; do
	echo "const uint8_t mock_frame_$(printf %02d ${NUM})[] = {"
	cat ${NAME} | xxd -i
	echo "};"
	echo
	NUM=$((NUM+1))
done

NUM=0
echo "const struct mock_frame mock_video[] = {"
for NAME in ${TMPDIR}/*; do
	framename=$(printf mock_frame_%02d ${NUM})	
	echo "    { .len = sizeof(${framename}), .data = &${framename} },"
	NUM=$((NUM+1))
done
echo "};"
echo "const unsigned int mock_video_frames = sizeof(mock_video)/sizeof(mock_video[0]);"
echo ""

rm -rf ${TMPDIR}
